### ISSUE TITLE
Stream version of `ReadStream`

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/blockmap#15]
Currently the `ReadStream` methods accept a `filename` parameter.
Would it make sense if there were equivalent versions of these functions which also took an already opened file-pointer / file-stream?

(I've not looked too in-depth at this project yet, so apologies if that's a silly question - but it's been inspired by all the other recent discussions around streaming...)

**Comment by jhermsmeier** [comment]
Yes, analog to node core's `fs.ReadStream` the read stream should support passing a `fd` option.

> took an already opened file-pointer / file-stream?

If you already have a readable stream of the file, you'll want to use `BlockMap.FilterStream()` (see [README.md#filtering-unmapped-blocks](https://github.com/resin-io-modules/blockmap#filtering-unmapped-blocks)) – ReadStreams on streams don't make much sense.

**Comment by lurch** [comment]
> see README.md#filtering-unmapped-blocks

Aha, having just re-read that code snippet twice I can see I was getting confused between the `fs readStream` and the `BlockMap readStream` ;-)
I wonder if that could by clarified, by e.g. giving the different stream variables different names, rather than always calling them `readStream`?
